In [1]:
import torch

In [2]:
a = torch.ones((8, 10))
b = torch.Tensor([
    [1, 2, 3],
    [4, 5, 6]
])
times = a.shape[0] // b.shape[0]
b = torch.tile(b, (times, 1))
c = torch.concat([a, b], dim=1)
a, b, c

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [1., 2., 3.],
         [4., 5., 6.],
         [1., 2., 3.],
         [4., 5., 6.],
         [1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 3.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 5., 6.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 3.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 5., 6.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 3.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 5., 6.],
         [1., 1., 1., 1., 